-- =============================================================
-- BANCOSOL ALIMENTOS - Datos de ejemplo
-- =============================================================

-- -------------------------------------------------------------
-- DIRECCION
-- -------------------------------------------------------------
INSERT INTO CAMPANYAS.DIRECCION (ZONA_GEOGRAFICA, DISTRITO) VALUES ('Axarquía', NULL);
INSERT INTO CAMPANYAS.DIRECCION (ZONA_GEOGRAFICA, DISTRITO) VALUES ('Málaga Capital', 'Centro');
INSERT INTO CAMPANYAS.DIRECCION (ZONA_GEOGRAFICA, DISTRITO) VALUES ('Málaga Capital', 'Este');
INSERT INTO CAMPANYAS.DIRECCION (ZONA_GEOGRAFICA, DISTRITO) VALUES ('Costa Occidental', NULL);
INSERT INTO CAMPANYAS.DIRECCION (ZONA_GEOGRAFICA, DISTRITO) VALUES ('Antequera', NULL);
INSERT INTO CAMPANYAS.DIRECCION (ZONA_GEOGRAFICA, DISTRITO) VALUES ('Benalmádena', NULL);
INSERT INTO CAMPANYAS.DIRECCION (ZONA_GEOGRAFICA, DISTRITO) VALUES ('Marbella', NULL);
INSERT INTO CAMPANYAS.DIRECCION (ZONA_GEOGRAFICA, DISTRITO) VALUES ('Estepona', NULL);
INSERT INTO CAMPANYAS.DIRECCION (ZONA_GEOGRAFICA, DISTRITO) VALUES ('Interior', NULL);
INSERT INTO CAMPANYAS.DIRECCION (ZONA_GEOGRAFICA, DISTRITO) VALUES ('Torremolinos', NULL);

-- -------------------------------------------------------------
-- USUARIO
-- -------------------------------------------------------------
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('administrador',     'Admin Bancosol',     'admin1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'JMCobos',            'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'Arantxa',            'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'Aragón',             'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'Diego',              'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'FranJimenez',        'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'Ladoux',             'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'Chamizo',            'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'MariLuz',            'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'Victoria',           'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'Torre',              'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'Morato',             'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('coordinador',        'Marbella',           'coord1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('capitan',            'Pepe Ávila',         'cap1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('responsable_entidad','María Vallejo',      'resp1234');
INSERT INTO CAMPANYAS.USUARIO (TIPO_USUARIO, NOMBRE, CONTRASENA) VALUES ('responsable_tienda', 'Responsable Lidl 1', 'resp1234');

-- -------------------------------------------------------------
-- CADENA
-- -------------------------------------------------------------
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('ALCAMPO',         1);
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('ALDI',            1);
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('CARREFOUR',       0);
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('DIA',             1);
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('EL CORTE INGLES', 0);
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('EL JAMON',        1);
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('EROSKI',          0);
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('LIDL',            1);
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('MAKRO',           0);
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('MAS',             1);
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('MERCADONA',       1);
INSERT INTO CAMPANYAS.CADENA (NOMBRE_CADENA, PARTICIPA_EN) VALUES ('SUMA',            0);

-- -------------------------------------------------------------
-- TIENDA
-- -------------------------------------------------------------
-- Carrefour (ID_CADENA=3) - Axarquía (ID_DIRECCION=1)
INSERT INTO CAMPANYAS.TIENDA (ID_CADENA, ID_DIRECCION, PARTICIPA, FRANQUICIA, LINEALES, RESENA_CADENA, DOMICILIO, CLASIFICACION)
    VALUES (3, 1, 1, 0, 1, 'CARREFOUR RINCON DE LA VICTORIA', 'c/ Arroyo de Totalán, nº 36 - CC LA VICTORIA', 'Ubi 28 Cli 45 Rec 16 Tot 89');
INSERT INTO CAMPANYAS.TIENDA (ID_CADENA, ID_DIRECCION, PARTICIPA, FRANQUICIA, LINEALES, RESENA_CADENA, DOMICILIO, CLASIFICACION)
    VALUES (3, 1, 1, 0, 3, 'CARREFOUR MARKET LA CALA',        'Plaza Don Antonio Estrada, s/n - La Cala del Moral', NULL);
INSERT INTO CAMPANYAS.TIENDA (ID_CADENA, ID_DIRECCION, PARTICIPA, FRANQUICIA, LINEALES, RESENA_CADENA, DOMICILIO, CLASIFICACION)
    VALUES (3, 1, 1, 0, 2, 'CARREFOUR EXPRESS RINCON',        'c/ Ronda, s/n', NULL);
INSERT INTO CAMPANYAS.TIENDA (ID_CADENA, ID_DIRECCION, PARTICIPA, FRANQUICIA, LINEALES, RESENA_CADENA, DOMICILIO, CLASIFICACION)
    VALUES (3, 2, 1, 0, 4, 'CARREFOUR EXPRESS MALAGA',        'Pasaje Tamayo y Baus, 2', NULL);
-- Mercadona (ID_CADENA=11) - Málaga Capital (ID_DIRECCION=2)
INSERT INTO CAMPANYAS.TIENDA (ID_CADENA, ID_DIRECCION, PARTICIPA, FRANQUICIA, LINEALES, RESENA_CADENA, DOMICILIO, CLASIFICACION)
    VALUES (11, 2, 1, 0, 2, 'MERCADONA CENTRO',               'Avda. de Andalucía, 10', NULL);
INSERT INTO CAMPANYAS.TIENDA (ID_CADENA, ID_DIRECCION, PARTICIPA, FRANQUICIA, LINEALES, RESENA_CADENA, DOMICILIO, CLASIFICACION)
    VALUES (11, 1, 1, 0, 2, 'MERCADONA AXARQUIA',             'Avda. Mediterráneo, 5 - Torre del Mar', NULL);
-- Lidl (ID_CADENA=8) - Costa Occidental (ID_DIRECCION=4)
INSERT INTO CAMPANYAS.TIENDA (ID_CADENA, ID_DIRECCION, PARTICIPA, FRANQUICIA, LINEALES, RESENA_CADENA, DOMICILIO, CLASIFICACION)
    VALUES (8, 4, 1, 0, 2, 'LIDL FUENGIROLA',                 'c/ Miguel Ángel, s/n', NULL);

-- -------------------------------------------------------------
-- COORDINADOR
-- -------------------------------------------------------------
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (2, 1, 'José M. Cobos',        0, '600000001', 'jmcobos@bancosol.es',     'Zona Axarquía - 40 tiendas');
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (3, 5, 'Arantxa',              0, '600000002', 'arantxa@bancosol.es',      'Zona Málaga Capital - 72 tiendas');
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (4, NULL, 'Cristóbal Aragón',  0, '600000003', 'aragon@bancosol.es',       'Zona Interior - 48 tiendas');
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (5, NULL, 'Diego Vázquez',     0, '600000004', 'diego@bancosol.es',        'Costa Occidental - 43 tiendas');
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (6, NULL, 'Fran Jiménez',      0, '600000005', 'franjimenez@colegiolosolivos.es', 'Entidad: Colegio Los Olivos - 12 tiendas');
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (7, NULL, 'Manuel Ladoux',     0, '600000006', 'ladoux@uma.es',            'Entidad: UMA - 10 tiendas');
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (8, NULL, 'Mari Carmen Chamizo', 0, '600000007', 'chamizo@bancosol.es',    'Benalmádena - 19 tiendas');
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (9, NULL, 'Mari Luz Pérez',    0, '600000008', 'mariluz@bancosol.es',      'Estepona - 16 tiendas');
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (10, NULL, 'María Victoria Ruiz', 0, '600000009', 'victoria@bancosol.es', 'Antequera - 11 tiendas');
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (11, NULL, 'Coord Torremolinos', 0, '600000010', 'torre@bancosol.es',     'Torremolinos - 14 tiendas');
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (12, NULL, 'Vicente Morato',   0, '600000011', 'morato@bancosol.es',       'Málaga - 26 tiendas');
INSERT INTO CAMPANYAS.COORDINADOR (ID_USUARIO, ID_TIENDA, NOMBRE_COMPLETO, CAPITAN, TELEFONO, EMAIL, OBSERVACIONES)
    VALUES (13, NULL, 'Zona Marbella',    0, '600000012', 'marbella@bancosol.es',     'Marbella - 45 tiendas');

-- -------------------------------------------------------------
-- CAMPANYA
-- -------------------------------------------------------------
INSERT INTO CAMPANYAS.CAMPANYA (TIPO_CAMPANYA, FECHA_INICIO, FECHA_FIN, ESTADO)
    VALUES ('primavera', '2025-04-25', '2025-04-27', 'cerrada');
INSERT INTO CAMPANYAS.CAMPANYA (TIPO_CAMPANYA, FECHA_INICIO, FECHA_FIN, ESTADO)
    VALUES ('GR',        '2025-11-28', '2025-11-30', 'activa');

-- -------------------------------------------------------------
-- CAMPANYA_CADENA  (cadenas que participan en cada campaña)
-- -------------------------------------------------------------
-- Primavera 2025 (ID_CAMPANYA=1): Alcampo, Aldi, DIA, El Jamon, Lidl, MAS, Mercadona
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (1, 1);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (1, 2);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (1, 4);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (1, 6);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (1, 8);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (1, 10);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (1, 11);
-- GR 2025 (ID_CAMPANYA=2): todas las anteriores + Carrefour
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (2, 1);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (2, 2);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (2, 3);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (2, 4);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (2, 6);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (2, 8);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (2, 10);
INSERT INTO CAMPANYAS.CAMPANYA_CADENA (ID_CAMPANYA, ID_CADENA) VALUES (2, 11);

-- -------------------------------------------------------------
-- ASIGNACION_COORDINADOR
-- -------------------------------------------------------------
-- GR 2025: JMCobos (ID=2) -> tiendas Carrefour Axarquía
INSERT INTO CAMPANYAS.ASIGNACION_COORDINADOR (ID_CAMPANYA, ID_TIENDA, ID_COORDINADOR) VALUES (2, 1, 2);
INSERT INTO CAMPANYAS.ASIGNACION_COORDINADOR (ID_CAMPANYA, ID_TIENDA, ID_COORDINADOR) VALUES (2, 2, 2);
INSERT INTO CAMPANYAS.ASIGNACION_COORDINADOR (ID_CAMPANYA, ID_TIENDA, ID_COORDINADOR) VALUES (2, 3, 2);
-- GR 2025: Arantxa (ID=3) -> Carrefour Express Málaga + Mercadona Capital
INSERT INTO CAMPANYAS.ASIGNACION_COORDINADOR (ID_CAMPANYA, ID_TIENDA, ID_COORDINADOR) VALUES (2, 4, 3);
INSERT INTO CAMPANYAS.ASIGNACION_COORDINADOR (ID_CAMPANYA, ID_TIENDA, ID_COORDINADOR) VALUES (2, 5, 3);
-- GR 2025: Diego (ID=5) -> Lidl Fuengirola
INSERT INTO CAMPANYAS.ASIGNACION_COORDINADOR (ID_CAMPANYA, ID_TIENDA, ID_COORDINADOR) VALUES (2, 7, 5);
-- Primavera 2025: JMCobos -> Mercadona Axarquía
INSERT INTO CAMPANYAS.ASIGNACION_COORDINADOR (ID_CAMPANYA, ID_TIENDA, ID_COORDINADOR) VALUES (1, 6, 2);

-- -------------------------------------------------------------
-- ENTIDAD_COLABORADORA
-- -------------------------------------------------------------
INSERT INTO CAMPANYAS.ENTIDAD_COLABORADORA (ID_DIRECCION, NOMBRE_COLABORADOR, DOMICILIO, LIGADO_A_BANCOSOL, TIPO, OBSERVACIONES, NUMERO_VOLUNTARIOS)
    VALUES (1, 'A0362-AYUNTAMIENTO DE ALMACHAR', 'Calle Almería, 14', 1, 'entidad', '10 voluntarios. Formación Jueves 30, a las 19:45', 10);
INSERT INTO CAMPANYAS.ENTIDAD_COLABORADORA (ID_DIRECCION, NOMBRE_COLABORADOR, DOMICILIO, LIGADO_A_BANCOSOL, TIPO, OBSERVACIONES, NUMERO_VOLUNTARIOS)
    VALUES (1, 'A0346-AYUNTAMIENTO DE MOCLINEJO', 'Plaza del Ayuntamiento, 1', 1, 'entidad', NULL, 8);
INSERT INTO CAMPANYAS.ENTIDAD_COLABORADORA (ID_DIRECCION, NOMBRE_COLABORADOR, DOMICILIO, LIGADO_A_BANCOSOL, TIPO, OBSERVACIONES, NUMERO_VOLUNTARIOS)
    VALUES (2, 'B0001-GUARDIA CIVIL MALAGA',      'Avda. de la Aurora, s/n',   0, 'entidad', NULL, 6);
INSERT INTO CAMPANYAS.ENTIDAD_COLABORADORA (ID_DIRECCION, NOMBRE_COLABORADOR, DOMICILIO, LIGADO_A_BANCOSOL, TIPO, OBSERVACIONES, NUMERO_VOLUNTARIOS)
    VALUES (2, 'B0002-COLEGIO NOVASCHOOL',        'c/ Compositor Lehmberg Ruiz, 3', 0, 'entidad', NULL, 12);
INSERT INTO CAMPANYAS.ENTIDAD_COLABORADORA (ID_DIRECCION, NOMBRE_COLABORADOR, DOMICILIO, LIGADO_A_BANCOSOL, TIPO, OBSERVACIONES, NUMERO_VOLUNTARIOS)
    VALUES (1, 'B0003-FAMILIA OBDULIA',           NULL, 0, 'familia', NULL, 3);

-- -------------------------------------------------------------
-- CONTACTO
-- -------------------------------------------------------------
-- Contactos de A0362-AYUNTAMIENTO DE ALMACHAR (ID_COLABORADOR=1)
INSERT INTO CAMPANYAS.CONTACTO (ID_COLABORADOR, NOMBRE, EMAIL, TELEFONO) VALUES (1, 'Mario Torre (Concejal)', NULL,                    '555555555');
INSERT INTO CAMPANYAS.CONTACTO (ID_COLABORADOR, NOMBRE, EMAIL, TELEFONO) VALUES (1, 'María Vallejo',          NULL,                    '666666666');
INSERT INTO CAMPANYAS.CONTACTO (ID_COLABORADOR, NOMBRE, EMAIL, TELEFONO) VALUES (1, 'Fijo Ayuntamiento',      NULL,                    '999999999');
-- Contactos de A0346-AYUNTAMIENTO DE MOCLINEJO (ID_COLABORADOR=2)
INSERT INTO CAMPANYAS.CONTACTO (ID_COLABORADOR, NOMBRE, EMAIL, TELEFONO) VALUES (2, 'Arantxa Villalba',       'avillalba@moclinejo.es', '666777777');

-- -------------------------------------------------------------
-- PARTICIPACION_VOLUNTARIOS
-- -------------------------------------------------------------
-- GR 2025, Carrefour Hiper (tienda 1), Ayto. Almachar (colab 1)
INSERT INTO CAMPANYAS.PARTICIPACION_VOLUNTARIOS (ID_CAMPANYA, ID_TIENDA, ID_COLABORADOR)
    VALUES (2, 1, 1);
-- GR 2025, Carrefour Hiper (tienda 1), Ayto. Moclinejo (colab 2)
INSERT INTO CAMPANYAS.PARTICIPACION_VOLUNTARIOS (ID_CAMPANYA, ID_TIENDA, ID_COLABORADOR)
    VALUES (2, 1, 2);
-- GR 2025, Mercadona Centro (tienda 5), Guardia Civil (colab 3)
INSERT INTO CAMPANYAS.PARTICIPACION_VOLUNTARIOS (ID_CAMPANYA, ID_TIENDA, ID_COLABORADOR)
    VALUES (2, 5, 3);

-- -------------------------------------------------------------
-- TURNO_POR_DIA
-- -------------------------------------------------------------
-- Participación 1 (Ayto.Almachar en Carrefour Hiper): Viernes mañana y tarde
INSERT INTO CAMPANYAS.TURNO_POR_DIA (ID_PARTICIPACION, DIA, HORARIO, HORA_INICIO, HORA_FIN)
    VALUES (1, 'Viernes', 'manyana',           '09:00', '14:00');
INSERT INTO CAMPANYAS.TURNO_POR_DIA (ID_PARTICIPACION, DIA, HORARIO, HORA_INICIO, HORA_FIN)
    VALUES (1, 'Viernes', 'tarde',             '17:00', '21:00');
-- Participación 2 (Ayto.Moclinejo en Carrefour Hiper): Sábado mañana y tarde
INSERT INTO CAMPANYAS.TURNO_POR_DIA (ID_PARTICIPACION, DIA, HORARIO, HORA_INICIO, HORA_FIN)
    VALUES (2, 'Sabado',  'manyana',           '09:00', '14:00');
INSERT INTO CAMPANYAS.TURNO_POR_DIA (ID_PARTICIPACION, DIA, HORARIO, HORA_INICIO, HORA_FIN)
    VALUES (2, 'Sabado',  'tarde',             '17:00', '21:00');
-- Participación 3 (Guardia Civil en Mercadona): Sábado jornada completa
INSERT INTO CAMPANYAS.TURNO_POR_DIA (ID_PARTICIPACION, DIA, HORARIO, HORA_INICIO, HORA_FIN)
    VALUES (3, 'Sabado',  'jornada_completa',  '09:00', '21:00');

-- -------------------------------------------------------------
-- VOLUNTARIO
-- -------------------------------------------------------------
-- Participación 1, turno Viernes mañana (ID_TURNO=1) - 2 voluntarios con horas distintas
INSERT INTO CAMPANYAS.VOLUNTARIO (ID_PARTICIPACION, ID_TURNO, ID_TIENDA, HORARIOS)
    VALUES (1, 1, 1, '09:00-11:00');
INSERT INTO CAMPANYAS.VOLUNTARIO (ID_PARTICIPACION, ID_TURNO, ID_TIENDA, HORARIOS)
    VALUES (1, 1, 1, '11:00-14:00');
-- Participación 1, turno Viernes tarde (ID_TURNO=2)
INSERT INTO CAMPANYAS.VOLUNTARIO (ID_PARTICIPACION, ID_TURNO, ID_TIENDA, HORARIOS)
    VALUES (1, 2, 1, '17:00-21:00');
-- Participación 2, turno Sábado mañana (ID_TURNO=3)
INSERT INTO CAMPANYAS.VOLUNTARIO (ID_PARTICIPACION, ID_TURNO, ID_TIENDA, HORARIOS)
    VALUES (2, 3, 1, '09:00-14:00');
-- Participación 3, turno Sábado completo (ID_TURNO=5)
INSERT INTO CAMPANYAS.VOLUNTARIO (ID_PARTICIPACION, ID_TURNO, ID_TIENDA, HORARIOS)
    VALUES (3, 5, 5, '09:00-21:00');
INSERT INTO CAMPANYAS.VOLUNTARIO (ID_PARTICIPACION, ID_TURNO, ID_TIENDA, HORARIOS)
    VALUES (3, 5, 5, '09:00-14:00');
