spring.application.name=proyectoBancosol
º
# URL de la base de datos (sustituye 'nombre_tu_db' por el tuyo)
# spring.datasource.url=jdbc:postgresql://localhost:5432/nombre_tu_db

# Credenciales de acceso
# spring.datasource.username=tu_usuario
# spring.datasource.password=tu_contraseña

# Driver de PostgreSQL
# pring.datasource.driver-class-name=org.postgresql.Driver
