spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp
spring.application.name=proyectoBancosol

# 1. Conexion Supabase (PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuracion de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
# Direct connection: spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true
# Le dice a Hibernate que estamos usando PostgreSQL
# Direct connection: spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect